source 'https://rubygems.org'

gem 'activerecord', require: 'active_record'
gem 'sinatra'
gem 'pg'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'pry'
gem 'rake'
gem 'json'
gem 'puma'
gem 'require_all'
gem 'open3'
gem 'shotgun'
